### ISSUE TITLE
你这项目怎么跑不起来

### ISSUE THREAD

**Issue by javaeryuan** [Han-YLun/SaaS_IHRM_Vue#4]
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js        

'webpack-dev-server' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! saas-ihrm@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the saas-ihrm@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:

**Comment by Han-YLun** [comment]
先删除项目node_modules，然后按照我在项目运行描述写的一次运行。

我这边是直接下载下来，通过命令是ok的。
![image](https://user-images.githubusercontent.com/44769070/79060293-f20bb600-7cb5-11ea-8775-62dc9820bac7.png)

**Comment by wyunsi** [comment]
"errcode":404,"errmsg":"不存在的api, 当前请求path为 /sys/login， 请求方法为 GET ，请确认是否定义此请求。","data":null}  登陆不了

**Comment by Dowhilex724** [comment]
为什么我按照配置登录报错 说是user.js文件里65行 error is not defined

**Comment by Han-YLun** [comment]
@wyunsi @Dowhilex724 这边前端按前端项目的README.md操作,我自己操作了下,是可以访问的,如果后端项目未部署,是访问不了的，点击登录会返回504.
![image](https://user-images.githubusercontent.com/44769070/95943732-2f91fd00-0e19-11eb-9f92-8b70b01ecbae.png)
