### ISSUE TITLE
这个不是视频里初始的代码吗

### ISSUE THREAD

**Issue by jijian1994** [Han-YLun/SaaS_IHRM_Vue#5]
你好，项目跑起来了。这个是您自己写的吗。因为看到和视频里的那个初始的不一样。点登录进不去主页，vue我也菜刚学，所以看不太懂

**Comment by Han-YLun** [comment]
1.项目代码不一样是因为项目里面有很多问题的，我一直在改里面的bug和删除一些无用的功能和增加一些其他的功能
2.登不进去是因为后台也要部署的，并且可能数据库的账户密码不同。

**Comment by lopeasd** [comment]
老哥加个qq（3342865499）好不好，部署不起来
